# Generated by Django 4.1.7 on 2023-08-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='account_id',
        ),
    ]
