# Generated by Django 4.1.7 on 2023-08-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_owner_id_wallet_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_id',
            new_name='uuid',
        ),
    ]
