# Generated by Django 4.1.7 on 2023-08-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_wallet_id_wallet_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user_uuid',
        ),
    ]
