# Generated by Django 4.1.7 on 2023-08-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_transaction_id_transactions_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='balance',
            new_name='amount',
        ),
    ]
