# Generated by Django 4.1.7 on 2023-08-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_balance_transactions_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Credit'), (2, 'Debit')]),
        ),
    ]
